insert into bike_manufacturers (manufacturer) values
('Royal Enfield'),
('Husqvarna'),
('Vincent Motorcycles'),
('Bombardier'),
('Jawa'),
('Peugeot Scooters'),
('BMW'),
('Honda'),
('MZ'),
('Harley Davidson'),
('Kawasaki'),
('KTM'),
('Piaggio'),
('Royal Enfield'),
('Suzuki'),
('Yamaha'),
('Aprilia'),
('Benelli'),
('Bimota'),
('Ducati'),
('Fantic Motor'),
('Gilera'),
('Italjet'),
('Moto Guzzi'),
('MV Agusta'),
('Cagiva'),
('Piaggio'),
('Norton'),
('Triumph'),
('Buell'),
('Indian'),
('Lambretta');
